// <auto-generated />
using System;
using Meals_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meals_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216122541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Meals_API.Models.MealSearch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("searchQuery")
                        .HasColumnType("TEXT");

                    b.Property<bool>("searchSuccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Searches", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
